### ISSUE TITLE
Codesandbox example doesn't work

### ISSUE THREAD

**Issue by jemikanegara** [liyuanqiu/echarts-for-svelte#2]
I wanna to give this package a try but your example in the codesandbox not working : https://codesandbox.io/s/nice-brattain-o5mik

**Comment by liyuanqiu** [comment]
> I wanna to give this package a try but your example in the codesandbox not working : https://codesandbox.io/s/nice-brattain-o5mik

Thank you for your feedback. I used to define the version of 'svelte' as 'latest' in this codesandbox, and `svelte` introduced some breaking changes in the version 3.16.0, which break this codesandbox. And now I've specified the version of 'svelte' to 3.15.0 and this codesandbox works again.

By the way, I do not have any intention to adapt to the `svelte` versions after 3.15.0, until `svelte` supports `Typescript`. So at the moment, you can not use `echarts-for-svelte` with `svelte>3.15.0`.

I'll close this issue now, but if you have any more questions about this thread, feel free to reopen it.
